<?php
include 'page.php';

function okved_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#okved":
      $output = '<p>'.  t("Информация об ОКВЭД") .'</p>';
      break;
  }
  return $output;
} // function okved_help


function okved_perm() {
  return array('access okved');
} // function okved_perm()

/**
 * Implementation of hook_menu().
 */
function okved_menu() {
  $items['okved'] = array(
    'title' => 'База ОКВЭД',
    'page callback' => 'razdels_page',
    'access arguments' => array('access okved'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['okved/rasdel/%'] = array(
    'title callback' => '_razdel_title_callback',
    'title arguments' => array(2),
    'page callback' => 'okveds_page',
    'page arguments' => array(2),
    'access arguments' => array('access okved'),
    'type' => MENU_CALLBACK,
  );
  
  $items['okved/search/%'] = array(
    'title' => 'Результаты поиска',
    'page callback' => 'okveds_search',
    'page arguments' => array(2),
    'access arguments' => array('access okved'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function _razdel_title_callback($base_string) {

  return rasdel_name($base_string);
}

function okveds_search($filter) {
  // Make sure you don't trust the URL to be safe! Always check for exploits.

return okveds_search_print($filter);
}

function okveds_page($first) {
  // Make sure you don't trust the URL to be safe! Always check for exploits.
  if (!is_numeric($first)) {
    // We will just show a standard "access denied" page in this case.
    drupal_access_denied();
    return;  // We actually don't get here.
  }

return okveds_print($first);
}

/**
 * Implementation of hook_block().
 */
function okved_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('ОКВЭд блок');
    return $blocks;
  }
  elseif ($op == 'view') {
    if (user_access('access content')) {
      $block['subject'] = 'ОКВЭД';

      $block['content'] = theme('feed_icon', url($feedurl), t('Syndicate'));
      $block['content'] .= '<div class="more-link">'. l(t('more'), 'okved', array('title' => t('View the site map to see more RSS feeds.'))) ."</div>\n";

      return $block;
    }
  }
}

function razdels_page() {

return razdels_print();
}

?>
